// Named bundles of every CaptionStyle field, selectable as a whole from
// CaptionStyleEditor. Picking one replaces the entire style; the granular
// controls below stay available for fine-tuning afterward.
//
// `category` groups cards in the theme picker's filter row (see
// CaptionStyleEditor.jsx's THEME_CATEGORIES) -- purely a UI grouping, not
// read by the backend. Every theme here is built entirely from fields the
// ASS/libass burn pipeline (captions.rs/segments.rs) already supports; see
// README's caption-theme-library section for what's deliberately NOT
// attempted (emoji, true gradients/glow, non-center alignment) and why.
export const CAPTION_THEMES = [
  {
    id: "cascade-bold",
    name: "Cascade Bold",
    description: "Big current phrase in yellow, trailing phrase small above — the reference TikTok/Reels look.",
    category: "Bold & Punchy",
    style: {
      font_family: "Impact",
      font_size: 84,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "none",
      words_per_line: 3,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "uppercase",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "cascade",
      accent_color: "#FFE600",
    },
  },
  {
    id: "impact-statement",
    name: "Impact Statement",
    description: "Huge white Impact text with a heavy drop shadow and no animation — a static hook line that hits hard and holds.",
    category: "Bold & Punchy",
    style: {
      style_mode: "classic",
      font_family: "Impact",
      font_size: 88,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 4,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "anton-headline",
    name: "Anton Headline",
    description: "Ultra-bold condensed Anton lettering in white — punchy, static, magazine-headline energy with no motion.",
    category: "Bold & Punchy",
    style: {
      style_mode: "classic",
      font_family: "Anton",
      font_size: 82,
      text_color: "#FFFFFF",
      outline_color: "#111111",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 1,
      shadow_size: 3,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "bebas-trending",
    name: "Bebas Trending",
    description: "Tall condensed Bebas Neue with wide letter spacing and crisp uppercase — the energetic, trending caption look.",
    category: "Bold & Punchy",
    style: {
      style_mode: "classic",
      font_family: "Bebas Neue",
      font_size: 78,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 5,
      text_transform: "uppercase",
      letter_spacing: 6,
      shadow_size: 2,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "clean-classic",
    name: "Clean Classic",
    description: "One flowing line with a karaoke fill — subtle, readable, no size/color jumps.",
    category: "Karaoke & Highlight",
    style: {
      font_family: "Arial",
      font_size: 66,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "karaoke",
      words_per_line: 5,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "none",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "classic",
      accent_color: "#FFE600",
    },
  },
  {
    id: "golden-karaoke",
    name: "Golden Karaoke",
    description: "Word-by-word karaoke fill from muted gray into a warm gold — smooth, high-retention word-by-word reveal.",
    category: "Karaoke & Highlight",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 64,
      text_color: "#FFD766",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "karaoke",
      words_per_line: 5,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 2,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "highlight-emphasis",
    name: "Highlight Emphasis",
    description: "One line, each word pops from gray to white as it's spoken.",
    category: "Karaoke & Highlight",
    style: {
      font_family: "Georgia",
      font_size: 62,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "highlight",
      words_per_line: 5,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "none",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "classic",
      accent_color: "#FFE600",
    },
  },
  {
    id: "pulse-highlight",
    name: "Pulse Highlight",
    description: "Each word pops from gray to hot pink against a subtle translucent bar — bold, punchy highlight reveal.",
    category: "Karaoke & Highlight",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 66,
      text_color: "#FF4D6D",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "highlight",
      words_per_line: 5,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#000000",
      background_opacity: 45,
      bold: true,
      italic: false,
    },
  },
  {
    id: "neon-pop",
    name: "Neon Pop",
    description: "Cyan cascade accent with a pop-in current phrase — higher-energy alternative to Cascade Bold.",
    category: "Cascade Spotlight",
    style: {
      font_family: "Impact",
      font_size: 80,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "middle",
      animation: "pop",
      words_per_line: 3,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "uppercase",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "cascade",
      accent_color: "#00E5FF",
    },
  },
  {
    id: "grape-box",
    name: "Grape Box",
    description: "Big current phrase in purple sitting on a solid violet bar, trailing phrase small above — a boxed grape-toned cascade look.",
    category: "Cascade Spotlight",
    style: {
      style_mode: "cascade",
      font_family: "Poppins",
      font_size: 76,
      text_color: "#FFFFFF",
      outline_color: "#3B0764",
      accent_color: "#A855F7",
      position: "bottom",
      animation: "none",
      words_per_line: 3,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#6D28D9",
      background_opacity: 85,
      bold: true,
      italic: false,
    },
  },
  {
    id: "beast-mode",
    name: "Beast Mode",
    description: "Massive uppercase current word in red with a heavy drop shadow — a high-contrast, aggressive cascade style.",
    category: "Cascade Spotlight",
    style: {
      style_mode: "cascade",
      font_family: "Anton",
      font_size: 86,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FF0000",
      position: "bottom",
      animation: "none",
      words_per_line: 2,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 8,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "one-word-focus",
    name: "One Word Focus",
    description: "One word fills the frame at a time in bold pink — the cleanest possible single-word focal point.",
    category: "Cascade Spotlight",
    style: {
      style_mode: "cascade",
      font_family: "Bebas Neue",
      font_size: 98,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FF5CAA",
      position: "middle",
      animation: "none",
      words_per_line: 1,
      text_transform: "uppercase",
      letter_spacing: 2,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "boxed-minimal",
    name: "Boxed Minimal",
    description: "Small white text on a solid dark box — low-key, subtitle-like.",
    category: "Minimal & Clean",
    style: {
      font_family: "Verdana",
      font_size: 54,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "none",
      words_per_line: 6,
      bold: false,
      italic: false,
      letter_spacing: 0,
      text_transform: "none",
      background: "box",
      background_color: "#000000",
      background_opacity: 75,
      shadow_size: 0,
      style_mode: "classic",
      accent_color: "#FFE600",
    },
  },
  {
    id: "minimalist-line",
    name: "Minimalist Line",
    description: "Small, light, unobtrusive white text with a thin outline — quiet captions that never compete with the footage.",
    category: "Minimal & Clean",
    style: {
      style_mode: "classic",
      font_family: "Poppins",
      font_size: 48,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 6,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 1,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: false,
      italic: false,
    },
  },
  {
    id: "soft-subtitle",
    name: "Soft Subtitle",
    description: "Off-white text on a soft dark bar with no animation — the familiar broadcast-subtitle style viewers already trust.",
    category: "Minimal & Clean",
    style: {
      style_mode: "classic",
      font_family: "Arial",
      font_size: 50,
      text_color: "#F2F2F2",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 7,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#000000",
      background_opacity: 60,
      bold: false,
      italic: false,
    },
  },
  {
    id: "cinematic-zoom",
    name: "Cinematic Zoom",
    description: "Elegant serif letters zoom softly into place with wide tracking near the top of frame — a cinematic title-card feel.",
    category: "Cinematic & Editorial",
    style: {
      style_mode: "classic",
      font_family: "Georgia",
      font_size: 58,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "top",
      animation: "zoom",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 8,
      shadow_size: 3,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: false,
      italic: false,
    },
  },
  {
    id: "typewriter-editorial",
    name: "Typewriter Editorial",
    description: "Monospace text that types itself out letter by letter on a soft dark bar — an editorial, report-style look.",
    category: "Cinematic & Editorial",
    style: {
      style_mode: "classic",
      font_family: "Courier New",
      font_size: 52,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "typewriter",
      words_per_line: 6,
      text_transform: "none",
      letter_spacing: 1,
      shadow_size: 0,
      background: "box",
      background_color: "#000000",
      background_opacity: 55,
      bold: false,
      italic: false,
    },
  },
  {
    id: "documentary-serif",
    name: "Documentary Serif",
    description: "Small italic serif captions, static and understated — the quiet, credible tone of a documentary lower-third.",
    category: "Cinematic & Editorial",
    style: {
      style_mode: "classic",
      font_family: "Georgia",
      font_size: 44,
      text_color: "#EDEDED",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 8,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 1,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: false,
      italic: true,
    },
  },
  {
    id: "gaming-neon",
    name: "Gaming Neon",
    description: "Saturated neon-green text that pops in over a dark translucent bar — bold gaming-stream energy without any real glow.",
    category: "Energetic & Neon",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 70,
      text_color: "#00FFAA",
      outline_color: "#000000",
      accent_color: "#FF00E5",
      position: "middle",
      animation: "pop",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 2,
      shadow_size: 6,
      background: "box",
      background_color: "#0D0D0D",
      background_opacity: 50,
      bold: true,
      italic: false,
    },
  },
  {
    id: "hustle-energy",
    name: "Hustle Energy",
    description: "Bright orange text that bounces in with every line — fast, energetic pacing for hustle and motivation content.",
    category: "Energetic & Neon",
    style: {
      style_mode: "classic",
      font_family: "Poppins",
      font_size: 68,
      text_color: "#FF7A00",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "bounce",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 3,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "frosted-glass",
    name: "Frosted Glass",
    description: "White text fades in over a barely-there light panel — the closest approximation to a frosted-glass caption card.",
    category: "Frosted & Soft",
    style: {
      style_mode: "classic",
      font_family: "Poppins",
      font_size: 54,
      text_color: "#FFFFFF",
      outline_color: "#3A3A3A",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "fade",
      words_per_line: 6,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#FFFFFF",
      background_opacity: 25,
      bold: false,
      italic: false,
    },
  },
  {
    id: "pastel-soft",
    name: "Pastel Soft",
    description: "Small pastel-pink text that gently fades in, no box, no shouting — a soft, calm caption style.",
    category: "Frosted & Soft",
    style: {
      style_mode: "classic",
      font_family: "Poppins",
      font_size: 46,
      text_color: "#FFD9E8",
      outline_color: "#333333",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "fade",
      words_per_line: 6,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: false,
      italic: false,
    },
  },
  {
    id: "frame-box",
    name: "Frame Box",
    description: "Bold white uppercase text locked inside a solid black frame — maximum-contrast boxed captions.",
    category: "Boxed & Framed",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 62,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 5,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#000000",
      background_opacity: 100,
      bold: true,
      italic: false,
    },
  },
  {
    id: "monoline-flow",
    name: "Monoline Flow",
    description: "One long flowing line with a gentle karaoke fill — minimal styling, more words per line, easy to read in one glance.",
    category: "Boxed & Framed",
    style: {
      style_mode: "classic",
      font_family: "Poppins",
      font_size: 50,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "karaoke",
      words_per_line: 8,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: false,
      italic: false,
    },
  },
  // 13 more themes below, inspired by general style archetypes surveyed
  // across commercial subtitle-template marketplaces (Adobe Stock, Envato
  // Elements) — Retro & Synthwave, Vibrant Colorful, Comic & Pop Art,
  // Elegant & Script, Corporate & Lower-Third are new categories those
  // surveys surfaced that weren't represented above. No specific paid
  // template's design, name, or asset was copied — only the general
  // archetype (color/font/motion vocabulary), same as remotion-captions-
  // themes/pycaps above. True glitch/scanline/chromatic-fringing textures
  // and gradient text (what actually sells a lot of "VHS"/"retro" paid
  // templates) aren't things this ASS/libass pipeline can render at all —
  // "Retro Arcade"/"Synthwave Neon" below approximate the vibe with
  // saturated neon color pairings instead, not a literal VHS effect.
  {
    id: "synthwave-neon",
    name: "Synthwave Neon",
    description: "Big magenta current phrase with a cyan outline glow — an 80s synthwave color pairing, cascade style.",
    category: "Retro & Synthwave",
    style: {
      style_mode: "cascade",
      font_family: "Bebas Neue",
      font_size: 82,
      text_color: "#FFFFFF",
      outline_color: "#FF2E9A",
      accent_color: "#00E5FF",
      position: "bottom",
      animation: "none",
      words_per_line: 3,
      text_transform: "uppercase",
      letter_spacing: 2,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "arcade-glow",
    name: "Arcade Glow",
    description: "Cyan-outlined cascade spotlight with a hot-magenta current word — a neon arcade-cabinet color scheme.",
    category: "Retro & Synthwave",
    style: {
      style_mode: "cascade",
      font_family: "Anton",
      font_size: 80,
      text_color: "#FFFFFF",
      outline_color: "#00FFF0",
      accent_color: "#FF2E9A",
      position: "middle",
      animation: "none",
      words_per_line: 2,
      text_transform: "uppercase",
      letter_spacing: 1,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "retro-arcade",
    name: "Retro Arcade",
    description: "Amber text on a deep-purple outline that bounces in on every line — an 80s arcade-cabinet color pairing.",
    category: "Retro & Synthwave",
    style: {
      style_mode: "classic",
      font_family: "Anton",
      font_size: 76,
      text_color: "#FFB800",
      outline_color: "#2D1B4E",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "bounce",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 4,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "electric-blue-pop",
    name: "Electric Blue Pop",
    description: "Saturated electric-blue text that pops in on every line — a bold, single-color social-media look.",
    category: "Vibrant Colorful",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 68,
      text_color: "#0080FF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "pop",
      words_per_line: 4,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 2,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "lime-punch",
    name: "Lime Punch",
    description: "Bright lime-green words highlight in one after another — a punchy, high-visibility single-color look.",
    category: "Vibrant Colorful",
    style: {
      style_mode: "classic",
      font_family: "Poppins",
      font_size: 66,
      text_color: "#C6FF00",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "highlight",
      words_per_line: 5,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "coral-splash",
    name: "Coral Splash",
    description: "Warm coral text that fades gently in and out — a soft, single-color vibrant look.",
    category: "Vibrant Colorful",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 64,
      text_color: "#FF6F61",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "fade",
      words_per_line: 5,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "comic-burst",
    name: "Comic Burst",
    description: "Bold yellow uppercase text that bounces in with a heavy shadow — a comic-book \"impact\" burst feel.",
    category: "Comic & Pop Art",
    style: {
      style_mode: "classic",
      font_family: "Anton",
      font_size: 80,
      text_color: "#FFEB00",
      outline_color: "#000000",
      accent_color: "#FF1493",
      position: "middle",
      animation: "bounce",
      words_per_line: 3,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 6,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "pop-art-bold",
    name: "Pop Art Bold",
    description: "Hot-pink uppercase text popping in over a bright cyan block — bold pop-art color blocking.",
    category: "Comic & Pop Art",
    style: {
      style_mode: "classic",
      font_family: "Impact",
      font_size: 76,
      text_color: "#FF1493",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "pop",
      words_per_line: 3,
      text_transform: "uppercase",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#00E5FF",
      background_opacity: 90,
      bold: true,
      italic: false,
    },
  },
  {
    id: "elegant-serif",
    name: "Elegant Serif",
    description: "Refined italic serif in a soft cream tone, static and understated — a luxury/wedding-brand caption feel.",
    category: "Elegant & Script",
    style: {
      style_mode: "classic",
      font_family: "Playfair Display",
      font_size: 54,
      text_color: "#F5E6C8",
      outline_color: "#2A2A2A",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 6,
      text_transform: "none",
      letter_spacing: 1,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: false,
      italic: true,
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    description: "Warm metallic-gold serif text that fades gently into view — an elegant, premium-brand look.",
    category: "Elegant & Script",
    style: {
      style_mode: "classic",
      font_family: "Playfair Display",
      font_size: 58,
      text_color: "#D4AF37",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "fade",
      words_per_line: 5,
      text_transform: "none",
      letter_spacing: 2,
      shadow_size: 0,
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      bold: true,
      italic: false,
    },
  },
  {
    id: "luxury-fade",
    name: "Luxury Fade",
    description: "Italic serif on a barely-there dark card, fading softly in — a quiet, premium-brand caption card.",
    category: "Elegant & Script",
    style: {
      style_mode: "classic",
      font_family: "Playfair Display",
      font_size: 52,
      text_color: "#FFFFFF",
      outline_color: "#1A1A1A",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "fade",
      words_per_line: 6,
      text_transform: "none",
      letter_spacing: 1,
      shadow_size: 0,
      background: "box",
      background_color: "#000000",
      background_opacity: 30,
      bold: false,
      italic: true,
    },
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "White text on a solid brand-blue bar, static and clean — a news/corporate lower-third look.",
    category: "Corporate & Lower-Third",
    style: {
      style_mode: "classic",
      font_family: "Montserrat",
      font_size: 50,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 7,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#1E5AA8",
      background_opacity: 100,
      bold: true,
      italic: false,
    },
  },
  {
    id: "corporate-minimal",
    name: "Corporate Minimal",
    description: "Navy text on a clean white card — an inverted, light corporate lower-third for bright footage.",
    category: "Corporate & Lower-Third",
    style: {
      style_mode: "classic",
      font_family: "Arial",
      font_size: 46,
      text_color: "#0F2A4A",
      outline_color: "#FFFFFF",
      accent_color: "#FFE600",
      position: "bottom",
      animation: "none",
      words_per_line: 7,
      text_transform: "none",
      letter_spacing: 0,
      shadow_size: 0,
      background: "box",
      background_color: "#FFFFFF",
      background_opacity: 92,
      bold: false,
      italic: false,
    },
  },
];

export function defaultTheme() {
  return CAPTION_THEMES[0];
}

// Rotated through by speaker_id (mod length) when auto-applying a style
// at a "Speaker change" suggestion -- deliberately chosen to roughly
// track captions.rs's own SPEAKER_COLORS palette (#FFE600 yellow,
// #00E5FF cyan, #FF4D8D pink, #7CFF6B green, used for cascade mode's
// per-speaker accent color and this app's diarization timeline bands),
// so an auto-styled speaker transition stays in the same visual family
// as how that speaker is already color-coded elsewhere, not an
// unrelated arbitrary pick.
const SPEAKER_ROTATION_THEME_IDS = ["cascade-bold", "neon-pop", "pulse-highlight", "lime-punch"];

// Picks a theme id to auto-apply for a suggestTransitionPoints result
// (captions.js), used by Timeline.jsx's "Auto-apply" action so accepting
// a suggestion doesn't require opening the full style editor. Priority
// order below is deliberate: a strong emotional/energetic signal wins
// over a same-moment pause, since the pause is often just what created
// room for the more interesting event to register as its own signal in
// the first place, not the main event itself. Every branch maps to a
// theme whose own name/description in themes.js already matches the
// vibe (see that file's descriptions) -- not an arbitrary pick.
export function autoThemeIdForSuggestion(reasons, speakerId) {
  if (reasons.includes("Emphasis")) return "beast-mode"; // "a high-contrast, aggressive cascade style"
  if (reasons.includes("Speaker change") && speakerId != null) {
    return SPEAKER_ROTATION_THEME_IDS[speakerId % SPEAKER_ROTATION_THEME_IDS.length];
  }
  if (reasons.includes("Speeds up")) return "hustle-energy"; // "fast, energetic pacing"
  if (reasons.includes("Slows down")) return "documentary-serif"; // "quiet, credible tone"
  if (reasons.includes("Long pause") || reasons.includes("Pause")) return "minimalist-line"; // "quiet captions"
  return defaultTheme().id;
}
