// Named bundles of every CaptionStyle field, selectable as a whole from
// CaptionStyleEditor. Picking one replaces the entire style; the granular
// controls below stay available for fine-tuning afterward.
export const CAPTION_THEMES = [
  {
    id: "cascade-bold",
    name: "Cascade Bold",
    description: "Big current phrase in yellow, trailing phrase small above — the reference TikTok/Reels look.",
    style: {
      font_family: "Impact",
      font_size: 76,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "none",
      words_per_line: 3,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "uppercase",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "cascade",
      accent_color: "#FFE600",
    },
  },
  {
    id: "clean-classic",
    name: "Clean Classic",
    description: "One flowing line with a karaoke fill — subtle, readable, no size/color jumps.",
    style: {
      font_family: "Arial",
      font_size: 60,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "karaoke",
      words_per_line: 5,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "none",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "classic",
      accent_color: "#FFE600",
    },
  },
  {
    id: "boxed-minimal",
    name: "Boxed Minimal",
    description: "Small white text on a solid dark box — low-key, subtitle-like.",
    style: {
      font_family: "Verdana",
      font_size: 48,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "none",
      words_per_line: 6,
      bold: false,
      italic: false,
      letter_spacing: 0,
      text_transform: "none",
      background: "box",
      background_color: "#000000",
      background_opacity: 75,
      shadow_size: 0,
      style_mode: "classic",
      accent_color: "#FFE600",
    },
  },
  {
    id: "neon-pop",
    name: "Neon Pop",
    description: "Cyan cascade accent with a pop-in current phrase — higher-energy alternative to Cascade Bold.",
    style: {
      font_family: "Impact",
      font_size: 72,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "middle",
      animation: "pop",
      words_per_line: 3,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "uppercase",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "cascade",
      accent_color: "#00E5FF",
    },
  },
  {
    id: "highlight-emphasis",
    name: "Highlight Emphasis",
    description: "One line, each word pops from gray to white as it's spoken.",
    style: {
      font_family: "Georgia",
      font_size: 56,
      text_color: "#FFFFFF",
      outline_color: "#000000",
      position: "bottom",
      animation: "highlight",
      words_per_line: 5,
      bold: true,
      italic: false,
      letter_spacing: 0,
      text_transform: "none",
      background: "none",
      background_color: "#000000",
      background_opacity: 70,
      shadow_size: 0,
      style_mode: "classic",
      accent_color: "#FFE600",
    },
  },
];

export function defaultTheme() {
  return CAPTION_THEMES[0];
}
